---
- name: Configure custom certificate for ingress
  hosts: localhost

  collections:
    - redhat.openshift

  tasks:
    - name: Authenticate to cluster
      block:
        - name: Log in
          redhat.openshift.openshift_auth:
            username: kubeadmin
            password: "{{ lookup('ENV','KUBEADMIN_PASSWORD') }}"
          register: openshift_auth_results

        - name: Get a list of all pods
          kubernetes.core.k8s_info:
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            kind: Pod
          register: pod_list

      always:
        - name: If login succeeded, log out
          when: openshift_auth_results.openshift_auth.api_key is defined
          redhat.openshift.openshift_auth:
            state: absent
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
